pub mod commit;
pub mod coupling;
pub mod domain;
pub mod extension;
/// API routes
pub mod health;
pub mod index;
pub mod ingest;
pub mod ledger;
pub mod merkaba;
pub mod metatron;
pub mod process;
pub mod system;
pub mod tic;
pub mod vector;
pub mod zk;
